package com.lifesathi.backend.reminder;

import java.time.Instant;
import java.util.UUID;

public record ReminderResponse(
        UUID id,
        String title,
        ReminderType type,
        Instant remindAt,
        RecurrenceInterval recurrenceInterval,
        boolean active,
        // Both null for a standalone reminder. Non-null means this row was
        // generated by a cascade -- the mobile app uses chainId to group it
        // under its parent instead of showing it as a plain reminder too
        // (GET /api/reminders returns every reminder, cascade-generated
        // ones included, so the client is what separates the two views).
        UUID chainId,
        Integer offsetDays
) {
    // Public rather than package-private: reminder.chain (a separate
    // package to Java, despite the name) builds these too, when returning
    // a cascade's generated offset reminders.
    public static ReminderResponse from(Reminder reminder) {
        return new ReminderResponse(
                reminder.getId(),
                reminder.getTitle(),
                reminder.getType(),
                reminder.getRemindAt(),
                reminder.getRecurrenceInterval(),
                reminder.isActive(),
                reminder.getChainId(),
                reminder.getOffsetDays()
        );
    }
}
